# Generated by Django 4.2.16 on 2024-12-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nekretnine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusertype',
            options={'verbose_name': 'User type', 'verbose_name_plural': 'User type'},
        ),
    ]
